ervices:
  react-app:
    container_name: client-container
    restart: always
    build: ./todo-frontend
    stdin_open: true
    ports: 
      - "5000:5000"
    networks:
      - mern-app
  api-server:
    container_name: api-container
    restart: always
    build: ./todo-api
    ports:
      - "8080:8080"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local